### ISSUE TITLE
Content for the header section

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/opendatahub.io#102]
## Objective
Edit, review, and suggest changes to the content below as a comment to this issue. Use the image attached as a reference of what the content will be rendered like. If content and wording looks good. Give a `lgmt` (looks good to me) in the comments of this issue, otherwise leave your suggestions.

## Current Content

**Title**: A Data & AI Platform for the Hybrid Cloud

**Call to action**: Get started _--naviagtes-->_ (Installation page/ Architecture of ODH) 

Design Example
---
<img width="938" alt="image" src="https://user-images.githubusercontent.com/12587674/233701773-9bfec13b-a3b8-4f91-9b4b-e440138bea93.png">

**Comment by shgriffi** [comment]
I am wondering if we want to keep the "A Data & AI Platform for the Hybrid Cloud" or rebrand this "An Intelligent Application Platform for the Hybrid Cloud".  @LaVLaS @jedemo thoughts?

**Comment by shgriffi** [comment]
Also, I agree that the Get Started should go directly to the docs, similar to Kubeflow.org.

**Comment by jedemo** [comment]
I don't have a strong view on this, but to me "Intelligent Application Platform" implies a broader scope than ODH (at least today). Also not sure "Intelligent Application Platform" is a well-understood industry description compared to "AI platform." Just wondering if there might be some confusion about the capabilities provided.

**Comment by shgriffi** [comment]
@Gkrumbach07 we are going to change the title of this to "An AI Platform for the Hybrid Cloud".  Thanks.
