### ISSUE TITLE
Content for community section

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/opendatahub.io#109]
## Objective
Edit, review, and suggest changes to the content below as a comment to this issue. Use the image attached as a reference of what the content will be rendered like. If content and wording looks good. Give a `lgmt` (looks good to me) in the comments of this issue, otherwise leave your suggestions.

## Current Content

- **Title**: Join the Open Data Hub community
- **Subtitle**: None
- **Content**: see image

Design Example
---
<img width="615" alt="image" src="https://user-images.githubusercontent.com/12587674/234416274-5831854e-b7eb-49ef-a341-6c0255667a7b.png">

**Comment by shgriffi** [comment]
This all looks good to me @Gkrumbach07.  Two minor things...

I'd replace the lorem ipsum with "Get involved with our discussions or contribute to the project!"

Under source code, you have GITHUB ORIGINATION.  Should be GITHUB ORGANIZATION.
