### ISSUE TITLE
Update the Getting-Started Images

### ISSUE THREAD

**Issue by jjasghar** [opendatahub-io/opendatahub.io#146]
It seems the getting started doc is 1.4.0
![CleanShot 2023-05-31 at 11 41 48](https://github.com/opendatahub-io/opendatahub.io/assets/810824/110ce213-ddaa-4671-b262-03abe27b1242)

With 1.6.0 there are more options:
<img width="1635" alt="CleanShot 2023-05-31 at 11 42 22@2x" src="https://github.com/opendatahub-io/opendatahub.io/assets/810824/4d2cbc55-dca6-4dfe-ab46-d4e3d0e30bf0">

I'm not sure where to put the PR in to fix this, but I'll attach the image too.

**Comment by jjasghar** [comment]
Done. https://github.com/opendatahub-io/opendatahub.io/pull/151

**Comment by Gkrumbach07** [comment]
pr merged
