### ISSUE TITLE
By default, it will not enable any component

### ISSUE THREAD

**Issue by adelton** [opendatahub-io/opendatahub.io#186]
The 2.X installation instructions at https://opendatahub.io/docs/quick-installation-new-operator/ say about the Create DataScienceCluster operation:

> in the components section, by clicking > it expands currently supported core components. To enable any component, specifically tick the box in each component section. By default, it will not enable any component.

However, with the 2.1.0 operator that I get from the OperatorHub today, I see the following enabled by default:

* dashboard
* datasciencepipelines
* modelmeshserving
* workbenches

Should the documentation be updated, or is it incorrect that by default in the form view, these four are enabled?

**Comment by adelton** [comment]
So do you say that the installation instructions are not correct in stating "By default, it will not enable any component"?

Updates of the documentation for other releases seem like a separate topic. It might be useful to start staging documentation updates for that in draft pull requests though.

**Comment by VaishnaviHire** [comment]
Yep, I think a better wording would be `The default example sest core components as enabled. Users can unset the values if needed during creation DataScienceCluster`.

However we do want to also note, that by default if for a component the value for `enabled` is not set, it is set to be false.

Regarding the upcoming release, created a tracking issue https://github.com/opendatahub-io/opendatahub.io/issues/191

**Comment by adelton** [comment]
I've added https://github.com/opendatahub-io/opendatahub.io/pull/192 to fix the "by default, nothing is enabled" problem.

**Comment by adelton** [comment]
> However, we do want to also note, that by default if for a component the value for enabled is not set, it is set to be false.

In the form view, there is no fiddling with the `enabled` text value.

If you think it makes sense to amend the YAML view section, please do it in separate PR. That section might also use a fresh screenshot to show all the components that the user can expect to find in the YAML by default, so there might be more work to be done for that case.

**Comment by adelton** [comment]
With https://github.com/opendatahub-io/opendatahub.io/pull/192 merged, this issue is resolved.
