### ISSUE TITLE
Dependencies link does not work, is it needed at all?

### ISSUE THREAD

**Issue by adelton** [opendatahub-io/opendatahub.io#188]
The 2.X installation instructions at https://opendatahub.io/docs/quick-installation-new-operator/ start section Create a DataScienceCluster instance with

1. Please ensure to go through [Dependencies](https://opendatahub.io/docs/quick-installation-new-operator/#dependencies) before create new DataScienceCluster instance.

The link with fragment `#dependencies` does not work because the section Dependencies below does not define the `name` attribute.

However, it is also not clear if it is necessary to meet the dependencies before proceeding with the DataScienceCluster instance installation (in which case the Dependencies section should likely be moved up), or if the dependencies can be met any time later (in which case this "Please ensure ..." step could be safely removed).

**Comment by shalberd** [comment]
@VaishnaviHire all good points, the link and anchor or name could be fixed. The question on whether dependencies need to be resolved / installed before ODH Cluster install or after is a good one.

**Comment by VaishnaviHire** [comment]
Yes, need to fix the link. 

For dependencies, they should be installed before the component is deployed. This has been fixed, where operator will wait for dependencies to be installed before deploying a component. This will be made available in upcoming ODH release. Ref Issue - https://github.com/opendatahub-io/opendatahub-operator/pull/497, https://github.com/opendatahub-io/opendatahub-operator/pull/385

**Comment by adelton** [comment]
So if I understand it correctly, DataScienceCluster instance does not need these dependencies, the components need. In that case let's just remove that step from the instructions because it is unnecessary at that point.
