### ISSUE TITLE
Update license from GPL to Creative Commons 4

### ISSUE THREAD

**Issue by shgriffi** [opendatahub-io/opendatahub.io#31]
I am proposing that we change the license for opendatahub.io from GPL to Creative Commons given it is a website and contains documentation.  This repository doesn't need the copyleft coverage from GPL.

**Comment by shgriffi** [comment]
Created #32 to address this change.

**Comment by anishasthana** [comment]
_can_ we just change licences like this? I'm not sure exactly how license changes work

**Comment by shgriffi** [comment]
@crobby @anishasthana @jkoehler-redhat @guimou are you all good with option 1?  If so, I'm happy to reach out to get approval.

**Comment by jkoehler-redhat** [comment]
@shgriffi I am ok with option 1.

**Comment by anishasthana** [comment]
Sounds like a plan!
