### ISSUE TITLE
Data Science Pipelines Version Issues

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/opendatahub.io#55]
The [1.4.0 release notes](https://github.com/opendatahub-io/opendatahub.io/blob/master/_posts/2022-10-31-odh-release-1.4.0-blog.md) list the Data Science Pipelines version as 1.3.1 and the [1.4.1 release notes](https://github.com/opendatahub-io/opendatahub.io/blob/master/_posts/2023-01-24-odh-release-1.4.1-blog.md) list the version as 1.2.1.

I assume that we didn't move back to an older version of Data Science Pipelines and one of the version numbers is incorrect.

**Comment by LaVLaS** [comment]
@strangiato Thx. This was a typo on my part as the downstream ODH repo and is fixed.
