### ISSUE TITLE
2021-02-02/odh-release-1.0.0-blog.html contains invalid KFDef URLs

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/opendatahub.io#7]
In https://opendatahub.io/news/2021-02-02/odh-release-1.0.0-blog.html the second and third  `KFDef` URLs return a 404:
- https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_openshift.v1.2.0.yaml
- https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_openshift.master.kfptekton.yaml
![image](https://user-images.githubusercontent.com/13068832/111684661-38319980-87e4-11eb-818d-30d3110af44d.png)

**Comment by ptitzler** [comment]
It appears that the kubeflow repository is undergoing restructuring. The files appear to be located in https://github.com/kubeflow/manifests/tree/master/distributions/kfdef now, e.g. https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift.v1.2.0.yaml

**Comment by ariescheurwater** [comment]
Hi @ptitzler, I added an update of the url to a pull request related to the same issue.
