### ISSUE TITLE
Unable to return to notebook image selection

### ISSUE THREAD

**Issue by davwhite** [opendatahub-io/opendatahub.io#72]
**Describe the bug**
Once the first notebook is created (new installation, OCP 4.12.0, ODH 1.4.2) cannot stop the notebook server.

**To Reproduce**
1. Create a new notebook using the Data Science image from the selection list. 
2. Add simple hello world code to the notebook. 
3. Return to hub control panel. "Access notebook server" option is selected, "Stop notebook server" is not. 
4. Click on "Stop notebook server". A prompt for confirming stopping the server appears. 
5. Click on "Stop Server"
6. Page returns to hub control panel with "Access notebook server" selected.

**Expected behavior**
Should return to image selection page for notebook.

**Comment by LaVLaS** [comment]
@davwhite I'm closing this since it appears to be a bug in an older release.  If it is still an issue in ODH 1.5 or 1.6, feel free to open a PR in the https://github.com/opendatahub-io/odh-dashboard/issues
