### ISSUE TITLE
Persona advantage layout

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/opendatahub.io#84]
_This issue is part of a a group of issues dedicated for upgrading the current website. All PRs will merge into the [refresh](https://github.com/opendatahub-io/opendatahub.io/tree/refresh) branch._

**Details**
- This component uses tabs to switch between personas
- Each persona has 2-3 problems that are solved by ODH and each problem has 2-4 feature related to that problem. The UI for this should be structured in a way where these sections are not repeated.
- this component will implement other components defined by in this issue. One possible solution is described bellow, but any solution would work fine as long as duplicate code is avoided.
- this component is layout component so it shouldn't take any params. The content will be provided later, so this issue only focuses on the UI. use placeholder data in the meantime.

In the image bellow:
- red boxed elements are components that will take in icon, title, and body, and optionally link
- orange boxed element is a component that takes an array of red box component props in addition to props for its title, body, and image, and link.
- links should be optional and not render if not provided
<img width="511" alt="Screenshot 2023-04-12 at 3 20 32 PM" src="https://user-images.githubusercontent.com/12587674/231575630-4314e357-97f9-451c-b7a3-ee5e794fbb0c.png">

**Mockup**
_The content is not the final revision but will give an idea of how the UI should look_
<img width="375" alt="Screenshot 2023-04-12 at 3 09 04 PM" src="https://user-images.githubusercontent.com/12587674/231572949-da52ebfc-30fd-4391-aef2-99040c772362.png">

**Notes**
This component should have no margins on the root element. All spacing will be covered by this components parent.

**Recommended Knowledge**
- React

**Acceptance Criteria**
 - [ ] UI/UX component reflects details defined

**Comment by ezidav** [comment]
@ezidav
