### ISSUE TITLE
Kubeflow installation guide points to a nonexistent kfdef 

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/opendatahub.io#9]
1. Go to: https://opendatahub.io/docs/kubeflow/installation.html#install-kubeflow-with-istio-enabled
2. See point no. 2, `NOTE` part: 
![image](https://user-images.githubusercontent.com/7453394/112980916-c994fa00-915a-11eb-8934-3d2ddf5c6bf3.png)
  Or see https://github.com/opendatahub-io/opendatahub.io/blob/master/pages/docs/kubeflow/installation.md#install-kubeflow-with-istio-enabled

The https://github.com/kubeflow/manifests/tree/master/kfdef doesn't exist anymore.

**Comment by ariescheurwater** [comment]
Hi @tumido, I created a pull request for this issue.
